package innkeeperclient

type (
	logger interface {
		Println(...interface{})
	}
	// InnkeeperClient api client
	InnkeeperClient interface {
		ProvisionHost(geoLoc string, sku string, count int, tenantid string, osarg string) (result ProvisionHostResponse, err error)
		GetTenants() (result GetTenantsResponse, err error)
	}
	// IkClient api struct
	IkClient struct {
		Host     string
		Port     int
		User     string
		Password string
		Log      logger
	}
	// ProvisionHostResponse -- autogen json struct from 
	// generated by http://json2struct.mervine.net/
	ProvisionHostResponse struct {
		Data []struct {
			Name    string `json:"name"`
			OobIP   string `json:"oob_ip"`
			OobPw   string `json:"oob_pw"`
			OobUser string `json:"oob_user"`
		} `json:"data"`
		Message string `json:"message"`
		Status  string `json:"status"`
	}

	// GetTenantsResponse -- auto json struct
	GetTenantsResponse struct {
		Data []struct {
			Slotid   int    `json:"slotid"`
			Tenantid string `json:"tenantid"`
		} `json:"data"`
		Message string `json:"message"`
		Status  string `json:"status"`
	}
	/*
			{
		    "status": "success",
		    "data": [{
		        "name": "host-07-25",
		        "oob_ip": "10.65.70.125",
		        "oob_user": "pezuser",
		        "oob_pw": "pezpass"
		    }],
		    "message": "ok"
			}
			{[{"slotid": 1, "tenantid": "tech-support-openstack"},
				{"slotid": 2, "tenantid": "photon"},
				{"slotid": 3, "tenantid": "pez-stage"},
				{"slotid": 4, "tenantid": "photon-2"}]}
	*/
)
