package innkeeperclient

type (
	logger interface {
		Println(...interface{})
	}
	// InnkeeperClient api client
	InnkeeperClient interface {
		ProvisionHost(sku string, tenantid string) (result *ProvisionHostResponse, err error)
		GetStatus(requestID string) (resp *GetStatusResponse, err error)
		GetTenants() (result GetTenantsResponse, err error)
	}
	// IkClient api struct
	IkClient struct {
		URI      string
		User     string
		Password string
		Log      logger
	}
	// ProvisionHostResponse -- autogen json struct from
	// { "status": "success", "data": [{"requestid": "28ac758e-a02c-11e5-9531-0050569b9b57"}], "message": "ok" }
	// generated by http://json2struct.mervine.net/
	ProvisionHostResponse struct {
		Data    []RequestData `json:"data"`
		Message string        `json:"message"`
		Status  string        `json:"status"`
	}

	//GetStatusResponse - a status response object
	GetStatusResponse struct {
		Data []struct {
			Name    string `json:"name"`
			OobIP   string `json:"oob_ip"`
			OobPw   string `json:"oob_pw"`
			OobUser string `json:"oob_user"`
		} `json:"data"`
		Message string `json:"message"`
		Status  string `json:"status"`
	}
	// GetTenantsResponse -- auto json struct
	//{[{"slotid": 1, "tenantid": "tech-support-openstack"},
	//			{"slotid": 2, "tenantid": "photon"},
	//			{"slotid": 3, "tenantid": "pez-stage"},
	//			{"slotid": 4, "tenantid": "photon-2"}]}
	GetTenantsResponse struct {
		Data    []TenantData `json:"data"`
		Message string       `json:"message"`
		Status  string       `json:"status"`
	}
	//RequestData - a request data object
	RequestData struct {
		RequestID string `json:"requestid"`
	}

	//TenantData - a tenant data object
	TenantData struct {
		Slotid   int    `json:"slotid"`
		Tenantid string `json:"tenantid"`
	}
	/*
			{
		    "status": "success",
		    "data": [{
		        "name": "host-07-25",
		        "oob_ip": "10.65.70.125",
		        "oob_user": "pezuser",
		        "oob_pw": "pezpass"
		    }],
		    "message": "ok"
			}
	*/
)
